### ISSUE TITLE
next loader uses umd build -> "Unexpected token '}'"

### ISSUE THREAD

**Issue by elmariachi111** [LIT-Protocol/lit-share-modal-v3#2]
gm, thought my recent PR would've fixed this but turns out, the issue is deeper.
When importing this module in a nextjs 12.2 app the loader seems to require the umd package, not the es package. Sample repo: https://github.com/elmariachi111/lit-test

`yarn build`
```
SyntaxError: Unexpected token '}'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.381 (/home/stadolf/work/tmp/lit-test/.next/server/pages/index.js:22:53)
    at __webpack_require__ (/home/stadolf/work/tmp/lit-test/.next/server/webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
```

dev mode:
![image](https://user-images.githubusercontent.com/1344649/178231672-195169f2-1f89-42e7-a385-3fe6c160ebfc.png)

Yesterday night I was building the repo locally and yarn linking it to my client dependencies. That actually worked out (after fixing the typo in #1 ).

**Comment by pawanpaudel93** [comment]
I was facing the same issue for Nextjs then I cloned the repo and updated the packages to the latest for both lit-share-modal-v3 and the project I am working on and copied the freshly built dist folder and now I am not getting the problems anymore.

**Comment by cnsndnz** [comment]
I have fixed the problem for myself. Install 'next-transpile-module' package and please change the next.config.js as below.

const withTM = require('next-transpile-modules')(['lit-share-modal-v3']);

```
const withTM = require('next-transpile-modules')(['lit-share-modal-v3']);

const nextConfig = withTM({
  reactStrictMode: true,
  swcMinify: true,
  i18n,
  images: {
    domains: ['picsum.photos'],
  },
}));
```
